default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: voting_development

test:
  <<: *default
  database: voting_test

production:
  <<: *default
  database: voting_production
  username: voting
  password: <%= ENV['VOTING_DATABASE_PASSWORD'] %>
